name: singlem_singlem
description: Taxonomic profiling of metagenomic sequence data using SingleM marker genes
keywords:
  - classify
  - metagenomics
  - fastq
  - taxonomic profiling
tools:
  - singlem:
      description: Marker gene-based taxonomic profiling of microbial communities from shotgun metagenomes
      homepage: https://github.com/wwood/singlem
      documentation: https://github.com/wwood/singlem#singlem-pipe
      tool_dev_url: https://github.com/wwood/singlem
      doi: "10.1186/s40168-018-0479-4"
      licence: ["MIT"]
      identifier: biotools:singlem
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
          List of input fastq/fasta files of size 1 and 2 for single-end and paired-end data,
          respectively.
        pattern: "*.{fastq,fq,fasta,fa,fsa,fas,fna,fastq.gz,fq.gz,fasta.gz,fa.gz,fsa.gz,fas.gz,fna.gz}"
        ontologies:
          - edam: http://edamontology.org/format_1930 # FASTQ
  - db:
      type: directory
      description: |
        Path to SingleM marker gene database or genome FASTA files (optional)
output:
  results:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.profile.tsv":
          type: file
          description: Taxonomic profile generated by SingleM
          pattern: "*.profile.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@talnor"
  - "@sofstam"
  - "@jfy133"
maintainers:
  - "@talnor"
  - "@sofstam"
  - "@jfy133"